./05-build.sh
./10-rabbitmq.sh
./13-mariadb.sh
./17-keystone-api.sh
./20-RUNONCE-service-endpoints.sh
./21-neutron-database.sh
./22-glance-database.sh
./23-ironic-database.sh
./24-nova-database.sh
./30-neutron-api.sh
./31-neutron-linuxbridge-agent.sh
./32-neutron-dhcp-agent.sh
./40-glance-api.sh
./45-glance-registry.sh
./50-ironic-api.sh
./51-ironic-imagedata.sh
./52-ironic-tftp.sh
./53-ironic-nginx.sh
./55-ironic-conductor.sh
./60-nova-api.sh
./61-nova-conductor.sh
./62-nova-scheduler.sh
./63-nova-compute.sh
