./17-keystone-api.sh
./20-RUNONCE-service-endpoints.sh
./21-neutron-database.sh
./22-glance-database.sh
./23-ironic-database.sh
./24-nova-database.sh
./25-swift-network.sh
./26-swift-ring.sh
./30-neutron-server.sh
./31-neutron-linuxbridge-agent.sh
./32-neutron-dhcp-agent.sh
./33-neutron-metadata-agent.sh
./34-RUNONCE-neutron-provider.sh
./40-swift-aio.sh
./50-glance-api.sh
./55-glance-registry.sh
./60-ironic-api.sh
./61-ironic-imagedata.sh
./62-ironic-tftp.sh
./63-ironic-nginx.sh
./65-ironic-conductor.sh
./67-ironic-agent.sh
./70-nova-placement.sh
./71-nova-api.sh
./72-nova-conductor.sh
./73-nova-scheduler.sh
./74-nova-compute.sh
