#!/bin/bash
set -x

ETCD_DATA_DIR=/var/lib/etcd \
ETCD_NAME=${CONTROL_HOST} \
ETCD_ADVERTISE_CLIENT_URLS="http://${CONTROL_HOST_IP}:2379,http://${CONTROL_HOST_IP}:4001" \
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001" \
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380" \
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://${CONTROL_HOST_IP}:2380" \
ETCD_INITIAL_CLUSTER="${CONTROL_HOST}=http://${CONTROL_HOST_IP}:2380" \
ETCD_INITIAL_CLUSTER_STATE=new \
ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_UUID} \
etcd
