FROM hogepodge/glance:centos
MAINTAINER chris@openstack.org
ADD /generate.glance-api.conf /generate.glance-api.conf
ADD /generate.glance-registry.conf /generate.glance-registry.conf
ADD /glance-api-paste.ini /etc/glance/glance-api-paste.ini
ADD /glance-registry-paste.ini /etc/glance/glance-registry-paste.ini
